version: '3'

services:

  mariadb_c:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - mariadb_v:/var/lib/mysql

  adminer_c:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mariadb_v:
