version: '3'

services:
  tomcat_c:
    image: tomcat
    ports:
      - 38080:8080
    volumes:
      #            . means folder container this .yml file
      -            ./usr/local/tomcat/webapps:/usr/local/tomcat/webapps
      # /path/in/localmachine/as/source/tomap:/path/in/container/tomap
