version: '3'

services:
  tomcat_c:
    image: tomcat
    ports:
      - 28080:8080
    volumes:
      #        . means folder container this .yml file
      -        ./usr/local/tomcat/webapps:/usr/local/tomcat/webapps
      #  /path/in/local/machine/as/source:/path/in/container/to/map
