version: '3'

services:

  dockerfile-assignment-1_c:
    image: dockerfile-assignment-1_i
    build:
      context   : ${build_context}
      dockerfile: ${build_dockerfile}
      #         : use absolute path for both :context n :dockerfile via envvar
    ports:
      - 21002:3000
