FROM python
CMD echo "python  `python  -V`"   ; \
    echo "python3 `python3 -V`"   ; \
    echo "pip     `           pip --version`"   ; \
    echo "pip     `python3 -m pip --version`"   ; \
    echo
