version: '3'

services:
  composeassignment1_c:
    depends_on:
      - es

    image: composeassignment1_i
    build:
      context:    .
      dockerfile: ./Dockerfile

    ports:
      - 5000:5000

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
